config/routes.rb
Rails.application.routes.draw do
  root "root#root"

  resources :job_recipes do
    member do
      post :launch
    end
  end
end

app/models/batch_config.rb
class BatchConfig < Settingslogic
  source "#{Rails.root}/config/batch.yml"
  namespace Rails.env
end

app/models/job_queue.rb
class JobQueue
  def self.enqueue!(job_recipe)
    recipe = YAML.load(job_recipe.recipe)
    recipe["options"] ||= {}
    recipe["options"]["job_recipe_id"] = job_recipe.id
    $redis.lpush(queue_name, YAML.dump(recipe))
  end

  def self.queue_name
    "job_queue"
  end
end

app/models/job_recipe.rb
class JobRecipe < ActiveRecord::Base
  self.table_name = "job_recipe"

  has_many :job_recipe_logs

  validates :name, presence: true
  validates :recipe, presence: true

  def enqueue!
    JobQueue.enqueue! self
  end
end

app/models/job_recipe_log.rb
class JobRecipeLog < ActiveRecord::Base
  self.table_name = "job_recipe_log"

  module STATUS
    PROGRESS = 0
    SUCCESS  = 1
    FAILURE  = 2
  end

  belongs_to :job_recipe

  scope :recent, ->(count) { order("`id` DESC").limit(count) }
  scope :progress, -> { where(status: STATUS::PROGRESS) }

  def progress?
    status == STATUS::PROGRESS
  end

  def success?
    status == STATUS::SUCCESS
  end

  def failure?
    status == STATUS::FAILURE
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_recipes_controller.rb
class JobRecipesController < ApplicationController
  def index
    @job_recipes = JobRecipe.all
    @working_job_logs = JobRecipeLog.progress
  end

  def show
    @job_recipe = JobRecipe.find(params[:id])

    @job_recipe_logs = @job_recipe.job_recipe_logs.recent(10)
  end

  def edit
    @job_recipe = JobRecipe.find(params[:id])
  end

  def update
    job_recipe = JobRecipe.find(params[:id])
    job_recipe.update!(job_recipe_params)

    redirect_to job_recipe
  end

  def new
    @job_recipe = JobRecipe.new
  end

  def create
    job_recipe = JobRecipe.create!(job_recipe_params)

    redirect_to job_recipe
  end

  def destroy
    job_recipe = JobRecipe.find(params[:id])
    job_recipe.destroy!
    redirect_to job_recipes_path
  end

  def launch
    job_recipe = JobRecipe.find(params[:id])
    job_recipe.enqueue!
    redirect_to job_recipe
  end

  private

  def job_recipe_params
    params.require(:job_recipe).permit(:name, :recipe)
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/job_recipes/_example_recipe.html.haml
%h2 Example Recipe
%pre
  :preserve
    job: sample_config
    options:
      timeout: 1000

app/views/job_recipes/_form.html.haml
.clearfix
  = form_for @job_recipe do |f|
    .form-group
      = f.label :name, "Job Name"
      = f.text_field :name, placeholder: "Sample job", class: "form-control"
    .form-group
      = f.label :recipe, "Recipe"
      = f.text_area :recipe, rows: 10, placeholder: "job: nop", class: "form-control"

    - if @job_recipe.id
      .form-group.clearfix
        %p.pull-right
          Created at #{@job_recipe.created_at},
          Updated at #{@job_recipe.updated_at}
      = f.submit "Update", class: "btn btn-default btn-lg pull-right"
    - else
      = f.submit "Create", class: "btn btn-default btn-lg pull-right"

  = render "example_recipe"

app/views/job_recipes/edit.html.haml
%h1.page-header Edit #{@job_recipe.name}

= render "form"

app/views/job_recipes/index.html.haml
%h1.page-header Job Recipes

.clearfix
  = link_to "New recipe", new_job_recipe_path, class: "btn btn-default btn-lg pull-right"

  %table.table.table-striped
    %thead
      %tr
        %th #
        %th Name
    %tbody
      - @job_recipes.each do |job_recipe|
        %tr
          %td= job_recipe.id
          %td
            = link_to job_recipe.name, job_recipe

%h2 Working jobs
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Start
    %tbody
      - @working_job_logs.each do |working_job_log|
        - job_recipe = working_job_log.job_recipe
        - if job_recipe
          %tr
            %td= link_to job_recipe.name, job_recipe
            %td= working_job_log.created_at

app/views/job_recipes/new.html.haml
%h1.page-header New Job Recipe

= render "form"

app/views/job_recipes/show.html.haml
%h1.page-header= @job_recipe.name

.clearfix
  = form_for @job_recipe, url: {action: :launch}, method: :post do
    = submit_tag "Launch", class: "btn btn-primary pull-right", data: { confirm: "Launch this job?" }

%h2 Job Definition
%pre= @job_recipe.recipe

.clearfix
  .pull-right
    = link_to "Edit recipe", edit_job_recipe_path, role: "button", class: "btn btn-default"
    = link_to "Delete recipe", @job_recipe, method: :delete, role: "button", class: "btn btn-danger", data: { confirm: "Delete this job?" }

%h2 Job Logs
%table.table.table-striped
  %thead
    %tr
      %th #
      %th Status
      %th Start
      %th Finish
  %tbody
    - @job_recipe_logs.each do |job_recipe_log|
      %tr
        %td= job_recipe_log.id
        %td
          - if job_recipe_log.progress?
            %span.label.label-info Progress
          - if job_recipe_log.success?
            %span.label.label-success Success
          - if job_recipe_log.failure?
            %span.label.label-danger Failure
        %td= job_recipe_log.created_at
        %td
          - unless job_recipe_log.progress?
            = job_recipe_log.updated_at

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title BatchSanConsole
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"
    = javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container-fluid
        .navbar-header
          = link_to "Batchsan Admin", "/", class: "navbar-brand"

    .container-fluid
      .row
        .col-sm-3.col-md-2.sidebar
          %ul.nav.nav-sidebar
            %li
              = link_to "Job Recipes", job_recipes_path

        .col-sm-9.col-sm-offset-3.col-md-10.col-md-offset-2.main
          = yield